services:
  web:
    build:
      context: .
      args:
        MIDJOURNEY_API_KEY: ${MIDJOURNEY_API_KEY}
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MIDJOURNEY_API_KEY=${MIDJOURNEY_API_KEY}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - PYTHONPATH=/app
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db

  celery:
    build:
      context: .
      args:
        MIDJOURNEY_API_KEY: ${MIDJOURNEY_API_KEY}
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    command: celery -A hloot worker --beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - MIDJOURNEY_API_KEY=${MIDJOURNEY_API_KEY}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - PYTHONPATH=/app
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - web
      - db

  frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  staticfiles:
  postgres_data:
