# Generated by Django 5.0.6 on 2024-06-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("playing", "Playing")],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
