# Generated by Django 5.0.6 on 2024-06-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_player",
                to="game.player",
            ),
        ),
    ]
