# Generated by Django 5.0.6 on 2024-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_game_current_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="current_round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="game",
            name="round_state",
            field=models.CharField(
                choices=[
                    ("PROMPT", "Prompt"),
                    ("IMAGE_GENERATION", "Image Generation"),
                    ("GUESSING", "Guessing"),
                    ("VOTING", "Voting"),
                ],
                default="PROMPT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[("WAITING", "Waiting"), ("PLAYING", "Playing")],
                default="WAITING",
                max_length=20,
            ),
        ),
    ]
