# Generated by Django 5.0.6 on 2024-06-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_game_current_round_game_round_state_alter_game_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="round",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
