# Generated by Django 5.0.6 on 2024-06-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_image_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="choice1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="choice2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="choice3",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="choice4",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="selection",
            field=models.URLField(blank=True, null=True),
        ),
    ]
