# Generated by Django 5.0.6 on 2024-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_image_choice1_image_choice2_image_choice3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="external_id",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
