# Generated by Django 5.0.6 on 2024-06-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_image_external_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "game")},
        ),
    ]
