# Generated by Django 5.0.6 on 2024-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_player_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="score",
        ),
        migrations.AlterField(
            model_name="game",
            name="round_state",
            field=models.CharField(
                choices=[
                    ("PROMPT", "Prompt"),
                    ("IMAGE_GENERATION", "Image Generation"),
                    ("GUESSING", "Guessing"),
                    ("PRESENTING", "Presenting"),
                ],
                default="PROMPT",
                max_length=20,
            ),
        ),
    ]
