# Generated by Django 5.0.6 on 2024-06-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_remove_player_score_alter_game_round_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="display_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="display_image",
                to="game.image",
            ),
        ),
    ]
