# Generated by Django 5.0.6 on 2024-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
