const styles = {
  container: {
    background: "url('https://cl.imagineapi.dev/assets/7ca88a00-35e3-4b39-81c1-c76c6e204e36.png') no-repeat center center fixed",
    backgroundSize: 'cover',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100vh',
    fontFamily: 'Arial, sans-serif',
  },
  centeredContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '100%',
    height: '100%',
  },
  gameCodeLabel: {
    fontSize: '2rem',
    color: '#555',
    marginBottom: '1rem',
  },
  gameCode: {
    fontSize: '4rem',
    color: 'white',
    WebkitTextStroke: '1.5px black',
    marginBottom: '2rem',
  },
  waitingContainer: {
    backdropFilter: 'blur(15px)',
    padding: '1rem',
    borderRadius: '8px',
    border: '2px',
  },
  waitingText: {
    fontSize: '1rem',
    color: 'white',
    noWrap: 'true',
  },
  playersList: {
    listStyleType: 'none',
    padding: 0,
  },
  playerItem: {
    fontSize: '2rem',
    color: 'white',
    padding: '0',
    marginTop: '0.75rem',
  },
  messageContainer: {
    backdropFilter: 'blur(15px)',
    paddingTop: '1vh',
    paddingBottom: '1vh',
    paddingLeft: '7vw',
    paddingRight: '7vw',
    borderRadius: '8px',
    textAlign: 'center',
    WebkitTextStroke: '1px #ccc',
  },
  highlightedText: {
    fontSize: '3rem',
    color: '#fff',
    marginBottom: '2rem',
    backdropFilter: 'blur(15px)',
  },
  polaroid: {
    backgroundColor: 'white',
    paddingTop: '1.5rem',
    paddingLeft: '1.5rem',
    paddingRight: '1.5rem',
    paddingBottom: '1.5rem',
    borderRadius: '10px',
    boxShadow: '0 0 15px rgba(0, 0, 0, 0.5)',
    textAlign: 'center',
    width: '80vh',
  },
  polaroidInner: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  largeImage: {
    width: '100%',
    borderRadius: '5px',
  },
  caption: {
    marginTop: '1.5rem',
    fontFamily: 'Arial, sans-serif',
    fontSize: '14px',
    color: '#333',
  },
  qrCode: {
    padding: '0.8rem',
    backgroundColor: 'white',
    backdropFilter: 'blur(15px)',
    borderRadius: '10px',
    marginBottom: '0rem',
  },
};

export default styles;
