const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    background: "url('https://cl.imagineapi.dev/assets/7ca88a00-35e3-4b39-81c1-c76c6e204e36.png') no-repeat center center fixed",
    backgroundSize: 'cover',
    backgroundColor: '#214a58',
    fontFamily: 'Arial, sans-serif',
    padding: '2rem',
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '2rem',
    borderRadius: '8px',
    fontSize: '2.5rem',
    width: '100%',
    maxWidth: '400px',
  },
  input: {
    fontSize: '1.5rem',
    padding: '0.5rem',
    marginBottom: '1rem',
    borderRadius: '4px',
    border: '1px solid #ccc',
    width: '100%',
    textAlign: 'center',
  },
  button: {
    fontSize: '1.5rem',
    padding: '0.5rem 1rem',
    borderRadius: '4px',
    border: 'none',
    backgroundColor: 'transparent',
    WebkitBackdropFilter: 'blur(20px)',
    backdropFilter: 'blur(20px)',
    color: '#fff',
    cursor: 'pointer',
    width: '100%',
    maxWidth: '300px',
    marginTop: '1rem',
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    marginLeft: '1.25rem',
  },
  textarea: {
    fontSize: '1rem',
    padding: '0.5rem',
    marginBottom: '1rem',
    borderRadius: '4px',
    border: '1px solid #ccc',
    width: '100%',
    height: '100px',
    boxSizing: 'border-box',
    marginRight: '8rem',
  },
  highlightedText: {
    fontSize: '2rem',
    color: '#fff',
    WebkitBackdropFilter: 'blur(15px)',
    backdropFilter: 'blur(15px)',
    borderRadius: '8px',
    paddingTop: '1vh',
    paddingBottom: '1vh',
    paddingLeft: '7vw',
    paddingRight: '7vw',
  },
  polaroid: {
    backgroundColor: 'white',
    padding: '1rem',
    paddingBottom: '2rem', // Thicker bottom padding to maintain the polaroid look even without caption
    border: '2px solid #ddd',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    width: '90%',
    maxWidth: '800px',
    marginBottom: '2rem',
    cursor: 'pointer',
  },
  polaroidInner: {
    paddingBottom: '1rem', // Additional padding to simulate thicker bottom for polaroid
  },
  largeImage: {
    width: '100%',
    height: 'auto',
  },
  waitingMessage: {
    fontSize: '3rem',
    color: 'white',
    WebkitTextStroke: '1px black',
    paddingLeft: '2rem',
    paddingRight: '2rem',
  },
  caption: {
    marginTop: '1rem',
    fontSize: '1rem',
    color: '#555',
    minHeight: '50px',
    maxHeight: '150px',
    overflowY: 'auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.5rem',
  },
  imagesContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '1rem',
  },
};

export default styles;
