const promptOptions = [
  "A fairy riding a giant snail through a magical forest with glowing mushrooms. Watercolor illustration.",
  "A haunted house on a hill with ghostly figures in the windows and a full moon in the background. Gothic comic.",
  "A robot bartender serving drinks to aliens in a futuristic space bar. 1950s retro-futurism.",
  "A floating island in the sky with upside-down trees and a waterfall flowing upwards. Salvador Dalí surrealism.",
  "A kitten wearing a wizard hat, casting a spell with tiny sparks flying around. Chibi anime.",
  "A Victorian-era detective investigating a mysterious case in a foggy London street. Classic noir.",
  "An explorer riding a giant turtle through a dense jungle, with ancient ruins in the background. Adventure cartoon.",
  "A flying steam-powered airship with intricate gears and cogs, soaring above a bustling city. Detailed steampunk illustration.",
  "A dragon and a knight locked in an epic battle on a mountaintop, with dramatic lightning in the sky. Epic fantasy.",
  "A serene lake with a mermaid sitting on a rock, surrounded by glowing fireflies and a starry night sky. Ethereal digital painting.",
  "A group of penguins having a picnic on an iceberg. Cartoon style.",
  "A pirate ship sailing through a storm with lightning striking the sea. Dramatic oil painting.",
  "A futuristic cityscape with flying cars and towering skyscrapers. Cyberpunk digital art.",
  "A cozy cabin in the woods during autumn, with colorful leaves falling. Impressionist painting.",
  "A knight in shining armor kneeling before a king in a grand medieval hall. Realistic historical art.",
  "A sunflower field under a bright blue sky with fluffy clouds. Van Gogh style.",
  "A space station orbiting a distant planet with astronauts floating outside. Space art.",
  "A magical library with floating books and glowing lanterns. Fantasy illustration.",
  "A Viking warrior standing on a rocky shore with a longship in the background. Norse mythology art.",
  "A quaint European village market with colorful stalls and bustling people. Folk art.",
  "A majestic lion sitting on a rock overlooking the savannah. Wildlife photography.",
  "A whimsical treehouse village high in the branches of giant trees. Children’s book illustration.",
  "A samurai warrior practicing with a katana in a tranquil Japanese garden. Ink wash painting.",
  "A bustling street scene in a futuristic Asian city at night. Neon-lit digital art.",
  "A group of aliens having a barbecue on Mars. Humorous comic style.",
  "A steampunk robot tinkering with a clockwork mechanism. Detailed illustration.",
  "A dragon curled around a treasure hoard in a dark cave. Fantasy art.",
  "A Renaissance-style portrait of a noblewoman in elaborate dress. Classic portrait art.",
  "A surreal landscape with melting clocks hanging from trees. Salvador Dalí surrealism.",
  "A detective in a trench coat and fedora examining clues in a dimly lit alley. Film noir style.",
  "A tropical beach with crystal clear water and palm trees swaying in the breeze. Tropical paradise.",
  "A gothic cathedral with intricate stained glass windows and towering spires. Architectural sketch.",
  "A cute puppy wearing a superhero cape and mask. Children's cartoon.",
  "A forest scene with a mystical unicorn drinking from a sparkling stream. Fantasy illustration.",
  "A bustling medieval market square with merchants and townsfolk. Historical illustration.",
  "A serene Zen garden with carefully raked sand and arranged rocks. Japanese garden art.",
  "A futuristic robot helping a child with homework in a cozy home. Futuristic domestic scene.",
  "A grand castle on a hilltop surrounded by a dense forest. Romantic landscape painting.",
  "A retro diner with classic cars parked outside and neon signs glowing. 1950s Americana.",
  "A wizard casting a spell in a dark and mysterious forest. Dark fantasy art.",
  "A colorful underwater scene with tropical fish and coral reefs. Marine life illustration.",
  "A snowy mountain landscape with a lone skier making their way down the slope. Winter sports art.",
  "A cybernetic warrior standing in a rain-soaked, neon-lit city street. Cyberpunk art.",
  "A farmer's market in a quaint countryside village with people buying fresh produce. Rustic illustration.",
  "A mystical portal opening in the middle of an ancient stone circle. Fantasy concept art.",
  "A fairy tale castle perched on a cliff overlooking the ocean. Storybook illustration.",
  "A superhero flying over a cityscape at sunset. Comic book art.",
  "A vintage steam train traveling through a picturesque landscape. Vintage travel poster.",
  "A modern dance performance with dancers in dynamic poses. Abstract art.",
  "A rustic kitchen with a warm hearth and freshly baked bread on the table. Cozy illustration.",
  "A serene lake at sunrise with mist rising from the water. Tranquil landscape painting.",
  "A knight and a dragon in an epic battle on a rocky cliff. Dramatic fantasy art.",
  "A playful scene of animals having a tea party in the forest. Whimsical children's illustration.",
  "A futuristic city with towering skyscrapers and flying vehicles. Sci-fi concept art.",
  "A cozy reading nook with a large window overlooking a rainy street. Cozy illustration.",
  "A detailed map of a fantasy world with mountains, rivers, and castles. Fantasy cartography.",
  "A bustling ancient Egyptian market with merchants and shoppers. Historical illustration.",
  "A dragon flying over a medieval village at sunset. Epic fantasy art.",
  "A futuristic landscape with alien plants and strange rock formations. Sci-fi illustration.",
  "A serene beach scene with seashells and gentle waves. Coastal art.",
  "A dark, enchanted forest with glowing eyes peering from the shadows. Dark fantasy illustration.",
  "A whimsical hot air balloon festival with colorful balloons in the sky. Festive art.",
  "A majestic phoenix rising from the ashes with flames around it. Mythical creature illustration.",
  "A futuristic laboratory with advanced technology and scientists working. Sci-fi concept art.",
  "A cozy fireplace with stockings hung and a decorated Christmas tree. Holiday illustration.",
  "A pirate treasure map with islands, sea monsters, and hidden coves. Adventure illustration.",
  "A peaceful mountain village with wooden cabins and smoke rising from chimneys. Rustic landscape.",
  "A detailed anatomical drawing of a fantastical creature. Scientific illustration.",
  "A bustling futuristic market with vendors selling alien goods. Sci-fi marketplace.",
  "A serene meadow with wildflowers and a gentle stream. Pastoral landscape painting.",
  "A steampunk inventor's workshop with gadgets and blueprints. Detailed illustration.",
  "A dramatic space battle with starships and laser beams. Space opera art.",
  "A whimsical scene of gnomes gardening in a magical garden. Fairy tale illustration.",
  "A futuristic sports event with athletes in high-tech gear. Sci-fi sports illustration.",
  "A mystical forest with glowing mushrooms and magical creatures. Fantasy illustration.",
  "A serene winter landscape with snow-covered trees and a frozen lake. Winter wonderland.",
  "A pirate ship anchored in a hidden cove with treasure chests. Adventure illustration.",
  "A bustling medieval town square with merchants and townsfolk. Historical illustration.",
  "A futuristic robot exploring an alien planet. Sci-fi exploration art.",
  "A cozy autumn scene with falling leaves and a warm cup of tea. Cozy fall illustration.",
  "A majestic dragon soaring over a fantasy kingdom. Epic fantasy art.",
  "A whimsical treehouse village with rope bridges and lanterns. Children's book illustration.",
  "A futuristic cityscape with towering skyscrapers and flying vehicles. Sci-fi concept art.",
  "A serene beach at sunset with seashells and gentle waves. Coastal art.",
  "A dark, enchanted forest with glowing eyes peering from the shadows. Dark fantasy illustration.",
  "A whimsical hot air balloon festival with colorful balloons in the sky. Festive art.",
  "A majestic phoenix rising from the ashes with flames around it. Mythical creature illustration.",
  "A futuristic laboratory with advanced technology and scientists working. Sci-fi concept art.",
  "A cozy fireplace with stockings hung and a decorated Christmas tree. Holiday illustration.",
  "A pirate treasure map with islands, sea monsters, and hidden coves. Adventure illustration.",
  "A peaceful mountain village with wooden cabins and smoke rising from chimneys. Rustic landscape.",
  "A detailed anatomical drawing of a fantastical creature. Scientific illustration.",
  "A bustling futuristic market with vendors selling alien goods. Sci-fi marketplace.",
  "A serene meadow with wildflowers and a gentle stream. Pastoral landscape painting.",
  "A steampunk inventor's workshop with gadgets and blueprints. Detailed illustration.",
  "A dramatic space battle with starships and laser beams. Space opera art.",
  "A whimsical scene of gnomes gardening in a magical garden. Fairy tale illustration.",
  "A futuristic sports event with athletes in high-tech gear. Sci-fi sports illustration.",
  "A mystical forest with glowing mushrooms and magical creatures. Fantasy illustration.",
  "A serene winter landscape with snow-covered trees and a frozen lake. Winter wonderland."
];

export default promptOptions;
