const promptOptions = [
  "A sinister castle looming under a blood-red moon, with shadows that seem to move on their own.",
  "A cozy cabin surrounded by autumn leaves, with smoke gently rising from the chimney and the smell of pumpkin spice in the air.",
  "A vibrant street festival with colorful decorations, where laughter fills the air and dancers twirl in a kaleidoscope of colors.",
  "A couple dancing under a starlit sky, with fireflies twinkling around them and soft music playing in the background.",
  "A quaint 1950s diner at dusk, with neon lights glowing and classic cars parked outside, as the jukebox plays rock 'n' roll hits.",
  "A bustling cityscape with neon lights reflecting off skyscrapers, as people rush by in a blur of modern fashion and energy.",
  "An enchanted forest with glowing mushrooms, where fairies flit about and ancient trees whisper secrets of old.",
  "A serene lake surrounded by lush greenery, with mist gently rising from the water and birds singing in the trees.",
  "A dreamlike landscape with melting clocks hanging from twisted trees, and impossible staircases leading to nowhere.",
  "A glamorous model posing in an elegant dress, with sparkling jewels and a backdrop of lavish opulence, as if ready for a red carpet event.",
  "A haunted carnival with eerie clowns, abandoned rides, and ghostly figures lurking in the shadows.",
  "A cozy autumn evening with a warm fire pit, friends gathered around with blankets, and marshmallows roasting on sticks.",
  "A magical library with floating books, twinkling lights, and a wise old librarian who seems to know every story ever written.",
  "A lively beach party at sunset, with tiki torches, vibrant music, and people dancing barefoot in the sand.",
  "A futuristic city with sleek skyscrapers, flying cars, and neon signs in every color of the rainbow.",
  "A spooky graveyard on a foggy night, with ancient tombstones, creeping vines, and ghostly apparitions wandering among the graves.",
  "A charming village square decorated for autumn, with pumpkins, hay bales, and children playing in the fallen leaves.",
  "A mystical mountain range with towering peaks, cascading waterfalls, and an ethereal glow from the setting sun.",
  "A serene Zen garden with raked sand, carefully placed rocks, and a gentle stream flowing through it.",
  "A whimsical tea party in a garden, with oversized flowers, delicate teacups, and colorful butterflies fluttering about.",
  "A spooky forest at twilight, with twisted trees, eerie shadows, and a haunting mist that creeps along the ground.",
  "A warm kitchen filled with the smell of freshly baked cookies, where a family gathers to share stories and laughter.",
  "A magical market at dusk, with stalls selling enchanted items, glowing lanterns, and mysterious figures browsing the wares.",
  "A lively concert in an open field, with a crowd dancing under a starry sky and the band playing energetic music.",
  "A spooky, abandoned house with broken windows, creaking floors, and whispers of ghostly inhabitants.",
  "A vibrant garden in full bloom, with a riot of colors from flowers, buzzing bees, and a gentle breeze carrying their fragrance.",
  "A cozy reading nook by a window, with soft cushions, a warm blanket, and a stack of beloved books.",
  "A mysterious cave with glowing crystals, ancient carvings, and a hidden treasure chest waiting to be discovered.",
  "A bustling market street in an old town, with vendors selling fresh produce, handmade crafts, and lively chatter filling the air.",
  "A haunted library with dusty bookshelves, flickering candles, and ghostly whispers echoing through the aisles.",
  "A serene countryside with rolling hills, a golden sunset, and a small cottage nestled among the trees.",
  "A whimsical carousel with brightly painted horses, twinkling lights, and children laughing as they ride.",
  "A spooky old lighthouse on a stormy night, with crashing waves, howling wind, and a ghostly figure watching from the top.",
  "A charming café on a rainy day, with the smell of fresh coffee, the sound of rain tapping on the windows, and a cozy atmosphere inside.",
  "A magical castle in the clouds, with soaring towers, shimmering spires, and a rainbow arcing across the sky.",
  "A lively dance floor with vibrant lights, pulsing music, and people lost in the rhythm of the night.",
  "A spooky haunted forest with twisted trees, eerie shadows, and a ghostly figure lurking in the mist.",
  "A tranquil beach at sunrise, with gentle waves, soft sand, and the first light of day breaking over the horizon.",
  "A bustling city street at night, with neon signs, busy sidewalks, and the hum of urban life.",
  "A spooky old mansion with creaking floors, cobweb-covered furniture, and ghostly faces appearing in the mirrors.",
  "A serene meadow in spring, with wildflowers in bloom, a gentle breeze, and the sound of birds singing.",
  "A whimsical circus with colorful tents, acrobats performing in the air, and the smell of popcorn and candy floss.",
  "A cozy living room on a snowy day, with a roaring fire, a soft blanket, and a steaming mug of hot chocolate.",
  "A spooky abandoned asylum with peeling paint, broken windows, and an unsettling silence.",
  "A vibrant carnival with bright lights, fun rides, and joyful laughter filling the air.",
  "A tranquil forest clearing with a gentle stream, dappled sunlight, and the sound of rustling leaves.",
  "A spooky haunted ship drifting through foggy waters, with ghostly sailors and tattered sails.",
  "A cozy autumn scene with a pumpkin patch, colorful leaves, and children playing in the crisp air.",
  "A magical forest with towering trees, glowing flowers, and mythical creatures hiding among the foliage.",
  "A lively street market with colorful stalls, the smell of fresh food, and the buzz of people bartering and chatting.",
  "A spooky graveyard at midnight, with crumbling tombstones, ghostly figures, and an eerie full moon overhead.",
  "A charming farmhouse with a red barn, golden fields, and animals grazing peacefully.",
  "A futuristic cityscape with sleek buildings, flying vehicles, and advanced technology everywhere you look.",
  "A whimsical bakery with colorful cakes, pastries, and the smell of fresh bread filling the air.",
  "A spooky forest trail with fog rolling in, twisted branches, and the feeling of being watched.",
  "A serene mountain lake with crystal clear water, surrounded by pine trees and the sound of nature.",
  "A lively music festival with vibrant lights, energetic crowds, and bands playing on multiple stages.",
  "A spooky haunted hotel with flickering lights, ghostly guests, and eerie corridors.",
  "A cozy cabin in the woods with a roaring fireplace, soft blankets, and the sound of rain on the roof.",
  "A magical kingdom with a grand castle, colorful banners, and knights on horseback.",
  "A bustling harbor at sunset, with ships docking, seagulls calling, and the smell of the sea in the air.",
  "A spooky old church with broken stained glass, flickering candles, and ghostly figures in the pews.",
  "A charming village covered in snow, with twinkling lights, festive decorations, and the sound of carolers singing.",
  "A vibrant garden party with colorful decorations, lively music, and guests enjoying themselves.",
  "A spooky forest with a full moon, howling wolves, and shadows that move on their own.",
  "A tranquil beach with palm trees, gentle waves, and a hammock swaying in the breeze.",
  "A bustling city market with vendors shouting, vibrant goods on display, and the smell of street food.",
  "A spooky haunted castle with cobwebs, flickering torches, and ghostly knights guarding the halls.",
  "A serene park in autumn, with golden leaves, a gentle breeze, and people enjoying a peaceful day.",
  "A lively fairground with bright lights, fun rides, and the smell of cotton candy and popcorn.",
  "A spooky swamp with thick fog, gnarled trees, and mysterious lights glowing in the distance.",
  "A cozy kitchen with the smell of baking bread, a warm oven, and a family gathered around the table.",
  "A magical forest glade with twinkling lights, soft moss, and the sound of a babbling brook.",
  "A bustling city street at Christmas, with festive decorations, carolers, and the smell of roasted chestnuts.",
  "A spooky old library with dusty books, creaking floors, and ghostly whispers.",
  "A serene meadow with wildflowers, butterflies, and the sound of a gentle breeze.",
  "A lively street parade with colorful floats, energetic dancers, and joyful music.",
  "A spooky haunted forest with twisted trees, eerie shadows, and a ghostly figure lurking in the mist.",
  "A cozy living room with a crackling fire, soft blankets, and the smell of hot cocoa.",
  "A magical night sky with twinkling stars, a glowing moon, and the silhouette of a flying dragon.",
  "A bustling city market with colorful stalls, the smell of fresh food, and the buzz of people bartering and chatting.",
  "A spooky old mansion with creaking floors, cobweb-covered furniture, and ghostly faces appearing in the mirrors.",
  "A serene mountain lake with crystal clear water, surrounded by pine trees and the sound of nature.",
  "A lively music festival with vibrant lights, energetic crowds, and bands playing on multiple stages.",
  "A spooky abandoned asylum with peeling paint, broken windows, and an unsettling silence.",
  "A cozy cabin in the woods with a roaring fireplace, soft blankets, and the sound of rain on the roof.",
  "A magical kingdom with a grand castle, colorful banners, and knights on horseback.",
  "A bustling harbor at sunset, with ships docking, seagulls calling, and the smell of the sea in the air.",
  "A spooky old church with broken stained glass, flickering candles, and ghostly figures in the pews.",
  "A charming village covered in snow, with twinkling lights, festive decorations, and the sound of carolers singing.",
  "A vibrant garden party with colorful decorations, lively music, and guests enjoying themselves.",
  "A spooky forest with a full moon, howling wolves, and shadows that move on their own.",
  "A tranquil beach with palm trees, gentle waves, and a hammock swaying in the breeze.",
  "A bustling city market with vendors shouting, vibrant goods on display, and the smell of street food."
];

export default promptOptions;
