name: CI, Tests, and Deploy to both GH Pages and Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install flake8
      run: pip install flake8
    - name: Run linter
      run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      MIDJOURNEY_API_KEY: "<fake-api-key>"
      DJANGO_SECRET_KEY: "django-insecure"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to the Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build, tag, and push web
      run: |
        docker build --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} -t registry.heroku.com/hloot/web .
        docker push registry.heroku.com/hloot/web

    - name: Build, tag, and push worker
      run: |
        docker build --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} -t registry.heroku.com/hloot/worker -f DockerfileWorker .
        docker push registry.heroku.com/hloot/worker

    - name: Release the app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web worker --app hloot

    - name: Scale dynos
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku ps:scale web=1 worker=1 --app hloot

  deploy-frontend:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
        working-directory: ./frontend

      - name: Build the React app
        env:
          REACT_APP_API_BASE_URL: https://hloot-9504ba8d8956.herokuapp.com/
        run: |
          echo "Building the React app..."
          npm run build
        working-directory: ./frontend

      - name: List build directory
        run: |
          echo "Listing contents of build directory..."
          ls -la ./frontend/build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
