name: Hloot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install flake8
      run: pip install flake8
    - name: Run linter
      run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      MIDJOURNEY_API_KEY: "<fake-api-key>"
      DJANGO_SECRET_KEY: "django-insecure"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: make test
